### ISSUE TITLE
tiny mute

### ISSUE THREAD

**Issue by brianboyer** [nprapps/elections14#1215] opened 2014-11-03 09:04 UTC
![screen shot 2014-11-03 at 4 04 21 am](https://cloud.githubusercontent.com/assets/68644/4880221/6ef06898-6338-11e4-9440-839ae105c7c3.png)

**Comment by alykat** [comment] 2014-11-03 14:52
Dupe of #1211

**Closed as completed by alykat** 2014-11-03 14:52 UTC
Labels: Priority: Low
